### ISSUE TITLE
Environment variable replacement potentionally breaks optimized/minimized javascript exports

### ISSUE THREAD

**Issue by rick-nu** [nstapelbroek/docker-static-webserver#13]
# What

I've ran into an issue where I thought Vite and NextJS weren't exporting files correctly. The browser was throwing exceptions when loading javascript resources.

After lots of debugging, I figured that the site only breaks whilst I was running it in the static -webserver. That got my suspicion going with the environment variable replacement.

## Diagnosis

This container replaces all variables with the following pattern: `${MY_ENVIRONMENT_VARIABLE}`. So I started searching for `${` in my static exported javascript files. It might not be a surprise anymore that modern javascript can use variables in backtick strings:

```
const string = `a string with a ${variable}`;
```

In recent exports, backtick strings became supported in all browsers, and this this is now valid browser compatible javascript.

Another finding was that empty variables also got replaced. So `${}` was just replaced with nothing.

## Desired solution

We might want to release a new version with different environment variable replacement. Options are:

- Only replace environment variables with a specific prefix, and put those as a filter in the `envsubst` command
- Find a different replacement method, and use `![[MY_ENVIRONMENT_VARIABLE]]` or something like that
- Add a variable that lists all the environment variables that should be replaced (whitelist)

## My workaround

How I solved it now in my personal project, was by overwriting `40-envsubst-on-www.sh` in the dockerfile, putting:

```shell
# Only replace variables in .html, .xml and .txt files
find "$www_dir" -regex '.*\.\(html\|xml\|txt\)$' -type f -exec sh -c 'envsubst < $0 > $0.tmp && mv $0.tmp $0' {} \;
```

**Comment by nstapelbroek** [comment]
I see, thanks for the heads up :)

I think replacing only with a specific prefix makes sense as this is a common practice in some bundlers like vite or meta frameworks like next.js. Plus, somehow filtering the call to envsubst might be less complex than revering back a "roll your own" replacement logic. 

let's explore that solution 👍

**Comment by nstapelbroek** [comment]
`envsubst` has a build in filter: https://superuser.com/questions/1148950/what-is-shell-format-in-envsubst. seems hopefull

**Comment by nstapelbroek** [comment]
I pushed a fix in [d1e7885](https://github.com/nstapelbroek/docker-static-webserver/commit/d1e788518a5a5df03af2d9d912342a8db5d0e741) and the `latest` docker image tag. 

You can now filter the environment variables that we'll be replacing by setting the `NGINX_ENVSUBST_FILTER` environment variable. This approach aligns perfectly with one of your desired solutions and was already a feature in the the [upstream nginx image](https://hub.docker.com/_/nginx). 

Before I publish this fix under the `4` tag. Can you or @eXistenZNL verify that this solution works on your project?

**Comment by rick-nu** [comment]
@nstapelbroek awesome! :muscle: 

If I understand correctly, setting the `NGINX_ENVSUBST_FILTER` will include all environment variables for replacement, als long as it contains the `NGINX_ENVSUBST_FILTER` right?

So with `NGINX_ENVSUBST_FILTER=MY_PROJECT`, the following will be replaced:

environment variable | Will be replaced
--- | ---
`$MY_PROJECT_URL` | yes
`${MY_PROJECT_NAME}` | yes
`$EXECUTE_MY_PROJECT` | yes
`$SOME_OTHER_VARIABLE` | no
`$environment` | no

Let me know and I will give it a try :ok_hand:

**Comment by nstapelbroek** [comment]
@rick-nu Correct, assuming that you're passing the environment variables it will only replace the onces you are filtering

text value in file | passed environment variable | passed nginx filter | result | why
--- | --- | --- | --- | --- 
`$MY_PROJECT_URL` | `MY_PROJECT_URL=123` | `PROJECT` | `123` | the passed filter matches we have an environment variable to replace
`${MY_PROJECT_URL}` | `MY_PROJECT_URL=123` | `PROJECT` | `123` | the passed filter matches and we have an environment variable to replace
\`${MY_PROJECT_URL}\` | `MY_PROJECT_URL=123` | `PROJECT` | \`123\` | the passed filter matches we have an environment variable to replace
`MY_PROJECT_URL` | `MY_PROJECT_URL=123` | `PROJECT` | `MY_PROJECT_URL` | this is not a valid form [for envsubst ](https://www.gnu.org/software/gettext/manual/html_node/envsubst-Invocation.html)
`$MY_PROJECT_URL` | `YOUR_PROJECT_URL=123` | `PROJECT` | `MY_PROJECT_URL` | the filter matches, but we have no environment variable to replace
`$MY_PROJECT_URL` | `MY_PROJECT_URL=123` | `PUBLIC_` | `MY_PROJECT_URL` | the variable does match the allowed filter


I'll update the docs a bit and release this as a new version.

**Comment by nstapelbroek** [comment]
This is now released as tag version `5`

**Comment by rick-nu** [comment]
@nstapelbroek I just used this in a new project, and it's absolutely perfect. Thank you once again! :heart:
