### ISSUE TITLE
/localhost/htdocs folder in /var/www

### ISSUE THREAD

**Issue by nstapelbroek** [nstapelbroek/docker-static-webserver#5]
The file / folder is created by default and should be removed

**Comment by rick-nu** [comment]
:+1:

I'm experiencing this issue too :D

**Comment by nstapelbroek** [comment]
Should be fixed now in latest!

**Comment by rick-nu** [comment]
@nstapelbroek awesome :D

**Comment by nstapelbroek** [comment]
@RickvdStaaij I started working on this project again last weekend and found a couple of bugs. If you're using this container. Expect a BC break soon in the latest tag. I'll poke you when it's ready

**Comment by rick-nu** [comment]
@nstapelbroek oh yes please :) Even though this is my current usage:

https://gitlab.enrise.com/Nawcast/NawcastRunner/blob/master/Dockerfile

**Comment by nstapelbroek** [comment]
@RickvdStaaij I just broke backward compatibility. If you would still like to use the old setup: There is an tag 0.1 available at https://hub.docker.com/r/nstapelbroek/static-webserver/tags/
