### ISSUE TITLE
Seperate vhost config from nginx

### ISSUE THREAD

**Issue by DanieloFleming** [nstapelbroek/docker-static-webserver#8]
i needed to overwrite some configuration in the vhost but in the current setup this requires a complete overwrite of nginx.conf

**Comment by nstapelbroek** [comment]
Fixed in `:latest`. I'll be releasing a new major version soon that should fix this.

**Comment by nstapelbroek** [comment]
Released in tag `2.0.0`. You can overwrite `/etc/nginx/vhost.conf`
